<script lang="ts">
	import ComparisonTable from '$lib/components/ComparisonTable.svelte';
	import { catalog, modelName } from '$lib/data/catalog.js';
	import { compareRuns } from '$lib/data/comparison.js';
	import { filterRuns, groupFamilies } from '$lib/data/explorer.js';
	let selected = $state(catalog.runs.slice(0,2).map((run) => run.id));
	let capability = $state(''); let hardware = $state(''); let runtime = $state(''); let family = $state('');
	let architecture = $state(''); let quant = $state(''); let memory = $state(''); let evidence = $state('');
	let visibleRuns = $derived(filterRuns(catalog.runs, catalog.models, { capability, hardware, runtime, family, architecture, quant, memory, evidence }));
	let groups = $derived(groupFamilies(catalog.models.filter((model) => visibleRuns.some((run: any) => run.modelSlug === model.slug)), visibleRuns));
	let runs = $derived(catalog.runs.filter((run) => selected.includes(run.id)));
	let comparison = $derived(compareRuns(runs));
	const options = (values: string[]) => [...new Set(values)].sort();
	function toggle(id: string) { selected = selected.includes(id) ? selected.filter((item) => item !== id) : [...selected,id]; }
</script>
<svelte:head><title>Compare runs — MetalBench</title><meta name="description" content="Compare local benchmark runs with compatibility checks and visible configuration differences." /></svelte:head>
<section class="page-head"><p class="eyebrow">COMPARISON DESK</p><h1>Compare runs without hiding the mismatches.</h1><p class="lede">Filters narrow the picker. They never weaken the compatibility gate.</p></section>
<section class="section compact"><div class="filter-grid compare-filters"><label>Capability<select bind:value={capability}><option value="">All</option>{#each options(catalog.models.flatMap((m) => m.capabilities)) as item (item)}<option value={item}>{item}</option>{/each}</select></label><label>Hardware<select bind:value={hardware}><option value="">All</option>{#each catalog.hardware as item (item.slug)}<option value={item.slug}>{item.name}</option>{/each}</select></label><label>Runtime<select bind:value={runtime}><option value="">All</option>{#each options(catalog.runs.map((r) => r.runtime.name)) as item (item)}<option>{item}</option>{/each}</select></label><label>Family<select bind:value={family}><option value="">All</option>{#each options(catalog.models.map((m) => m.familySlug)) as item (item)}<option value={item}>{catalog.models.find((m) => m.familySlug === item)?.family}</option>{/each}</select></label><label>Architecture<select bind:value={architecture}><option value="">All</option>{#each options(catalog.models.map((m) => m.architecture)) as item (item)}<option value={item}>{item}</option>{/each}</select></label><label>Quant range<select bind:value={quant}><option value="">All</option><option value="2-or-less">2-bit or lower</option><option value="3-4">3–4-bit</option><option value="5-6">5–6-bit</option><option value="7-8">7–8-bit</option><option value="special">Special formats</option></select></label><label>Measured memory<select bind:value={memory}><option value="">All</option><option value="under-6">Under 6 GiB</option><option value="6-12">6–12 GiB</option><option value="12-plus">12+ GiB</option><option value="unmeasured">Not measured</option></select></label><label>Evidence level<select bind:value={evidence}><option value="">All</option>{#each options(catalog.runs.map((r) => r.evidence.level)) as item (item)}<option value={item}>{item}</option>{/each}</select></label></div>
	<fieldset><legend>Select two or more runs</legend>{#each groups as group (group.slug)}<details class="picker-group" open><summary>{group.name}</summary><div class="check-grid">{#each group.configurations as configuration (configuration.model.slug)}{#each configuration.runs as run (run.id)}<label><input type="checkbox" checked={selected.includes(run.id)} onchange={() => toggle(run.id)} /><span><strong>{modelName(run.modelSlug)}</strong><small>{run.benchmarkSlug} · {run.runtime.name} · {run.runtime.quant}</small></span></label>{/each}{/each}</div></details>{/each}</fieldset>
	<div class:good={comparison.compatible} class="compat" aria-live="polite"><strong>{comparison.compatible ? 'Comparable' : 'Comparison blocked'}</strong>{#each comparison.reasons as reason (reason)}<span>{reason}</span>{/each}{#each comparison.warnings as warning (warning)}<span class="warning">Warning: {warning}</span>{/each}{#if comparison.compatible && !comparison.recommendationEligible}<span>External results cannot determine a local winner.</span>{/if}</div>
	{#if runs.length}<ComparisonTable {runs} />{/if}
</section>
